# Embed the head fit's SPIR-V into a C++ header (kernels/embed_spv.py's
# output shape, in Elixir: no Python, RFD 2239). The guest has no
# filesystem, so a GPU path would ship its kernels inside the ELF; each
# .spv becomes one `static const uint8_t` array plus a name -> bytes table.
#
#     elixir kernels/headfit/embed_spv.exs <namespace> <spv dir> <out.inc>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[ns, dir, out] =
  case System.argv() do
    [a, b, c] -> [a, b, c]
    _ -> IO.puts(:stderr, "usage: embed_spv.exs <namespace> <spv dir> <out.inc>") && System.halt(2)
  end

files = dir |> Path.join("*.spv") |> Path.wildcard() |> Enum.sort()
if files == [], do: (IO.puts(:stderr, "no .spv under #{dir}") && System.halt(1))

ident = fn name -> String.replace(name, ~r/[^A-Za-z0-9]/, "_") end

arrays =
  Enum.map(files, fn f ->
    name = Path.basename(f, ".spv")
    bytes = File.read!(f)

    rows =
      bytes
      |> :binary.bin_to_list()
      |> Enum.map(&"0x#{String.pad_leading(Integer.to_string(&1, 16), 2, "0")}")
      |> Enum.chunk_every(16)
      |> Enum.map_join(",\n", &("\t" <> Enum.join(&1, ", ")))

    {name, "static const uint8_t k_#{ident.(name)}[#{byte_size(bytes)}] = {\n#{rows}\n};\n"}
  end)

table =
  arrays
  |> Enum.map_join(",\n", fn {name, _} -> "\t{ \"#{name}\", k_#{ident.(name)}, sizeof(k_#{ident.(name)}) }" end)

text =
  "// Generated by kernels/headfit/embed_spv.exs from #{Path.basename(dir)}/. Do not edit; regenerate.\n" <>
    "#pragma once\n#include <cstddef>\n#include <cstdint>\n\nnamespace #{ns} {\n\n" <>
    Enum.map_join(arrays, "\n", fn {_, a} -> a end) <>
    "\nstruct Kernel {\n\tconst char *name;\n\tconst uint8_t *bytes;\n\tsize_t size;\n};\n\n" <>
    "static const Kernel kKernels[] = {\n#{table}\n};\n" <>
    "static const size_t kKernelCount = sizeof(kKernels) / sizeof(kKernels[0]);\n\n} // namespace #{ns}\n"

File.write!(out, text)
IO.puts("embed_spv: #{length(files)} kernels -> #{out}")
