# Writes guest/headfit/local_dials.txt from ANNY's MPFB2 target.json: the
# head fit's local dials, one per two-sided category of the head, chin,
# cheek, forehead, mouth, nose and eyebrows groups.
#
#   elixir guest/headfit/local_dials.exs [ANNY_DATA] > guest/headfit/local_dials.txt
#
# ANNY_DATA defaults to ~/contract-manifest/3-interactor/anny/src/anny/data.
# Line format (hf_core.cpp parse_dials): `group name pos[,pos] neg[,neg]`, the
# files relative to mpfb2/targets/<group>/ without .target; a sided dial lists
# its l- and r- files together, so both sides move as one unknown.
# Categories with a single target and no opposite (the head-shape presets and
# chin-triangle) are not dials: they are listed as comments and left out.
# SPDX-License-Identifier: Apache-2.0 OR MIT

data = List.first(System.argv()) || Path.expand("~/contract-manifest/3-interactor/anny/src/anny/data")
json = Path.join(data, "mpfb2/targets/target.json") |> File.read!() |> JSON.decode!()
groups = ~w(head chin cheek forehead mouth nose eyebrows)

IO.puts("# guest/headfit/local_dials.txt -- generated by guest/headfit/local_dials.exs from")
IO.puts("# ANNY mpfb2/targets/target.json; do not edit by hand.")
IO.puts("# group name pos[,pos] neg[,neg]")

{dials, skipped} =
  for g <- groups, c <- json[g]["categories"], reduce: {[], []} do
    {d, s} ->
      o = c["opposites"] || %{}

      {pos, neg} =
        if c["has_left_and_right"] do
          {[o["positive-left"], o["positive-right"]], [o["negative-left"], o["negative-right"]]}
        else
          {[o["positive-unsided"]], [o["negative-unsided"]]}
        end

      if Enum.any?(pos ++ neg, &(&1 in [nil, ""])) do
        {d, [{g, c["name"], c["targets"]} | s]}
      else
        for f <- pos ++ neg do
          p = Path.join([data, "mpfb2/targets", g, f <> ".target.gz"])
          File.exists?(p) || raise "missing #{p}"
        end

        {[{g, c["name"], pos, neg} | d], s}
      end
  end

for {g, n, pos, neg} <- Enum.reverse(dials) do
  IO.puts("#{g} #{n} #{Enum.join(pos, ",")} #{Enum.join(neg, ",")}")
end

IO.puts("# #{length(dials)} dials; skipped (one target, no opposite): #{length(skipped)}")

for {g, n, t} <- Enum.reverse(skipped) do
  IO.puts("# skipped #{g} #{n} (#{Enum.join(t, ",")})")
end
